projects:
  database:
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: prisma.yml
  app:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
